complexity:
  LongMethod:
    active: true
    threshold: 100
    ignoreAnnotated:
      - Composable

  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - Composable

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - Composable

style:
  ReturnCount:
    active: true
    max: 4
    excludedFunctions:
      - equals
